#!/usr/bin/env python3
"""Regenerate main/web_index.h from main/web/index.html (run after editing the page).

The page is stored gzip-compressed in a C array, so the firmware needs no
EMBED_TXTFILES step (which PlatformIO does not run) and sends ~4x fewer bytes.
"""
import gzip
from pathlib import Path

here = Path(__file__).resolve().parent
src = here / "main" / "web" / "index.html"
dst = here / "main" / "web_index.h"

raw = src.read_bytes()
gz = gzip.compress(raw, compresslevel=9, mtime=0)
lines = [", ".join(f"0x{b:02x}" for b in gz[i:i + 16]) for i in range(0, len(gz), 16)]
dst.write_text(
    "/* Generated by gen_web_index.py from main/web/index.html - do not edit. */\n"
    "#pragma once\n\n#include <stddef.h>\n#include <stdint.h>\n\n"
    f"/* {len(raw)} bytes of HTML, gzip-compressed */\n"
    "static const uint8_t WEB_INDEX_GZ[] = {\n    " + ",\n    ".join(lines) + "\n};\n"
    "static const size_t WEB_INDEX_GZ_LEN = sizeof(WEB_INDEX_GZ);\n",
    newline="\n")
print(f"{src.name}: {len(raw)} -> {len(gz)} bytes gzip -> {dst.relative_to(here)}")
